# Generated by Django 5.2.7 on 2025-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_image', models.JSONField(default=list)),
                ('keyword', models.JSONField(blank=True, default=list, null=True)),
                ('content', models.JSONField(default=list)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_image', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_image', models.JSONField(default=list)),
                ('keyword', models.JSONField(blank=True, default=list, null=True)),
                ('content', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_image', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.JSONField(default=list)),
                ('product_description', models.CharField(max_length=525)),
                ('main_application', models.JSONField(default=list)),
                ('benefit', models.JSONField(default=list)),
                ('performance', models.JSONField(default=list)),
                ('position', models.PositiveIntegerField(default=1, help_text='Display order position')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_image', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('site_area', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=255)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_type', models.IntegerField(choices=[(1, 'Single Image'), (2, 'Two Image'), (3, 'Three Image'), (4, 'Four Image')], default=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1, help_text='Display order position')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(default='Unknown', max_length=255)),
                ('auto_reply_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
