# Generated by Django 5.2.7 on 2025-10-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='success',
            new_name='main_application',
        ),
    ]
