# Generated by Django 5.2.7 on 2025-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
