# Generated by Django 5.2.7 on 2025-10-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0002_article_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.JSONField(default=list),
        ),
    ]
