# Generated by Django 5.2.7 on 2025-10-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0003_auto_20251024_1209'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP TABLE IF EXISTS CMSapp_articleimage;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
