# Generated by Django 5.2.7 on 2025-11-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0003_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
    ]
