# Generated by Django 5.2.7 on 2025-11-19 02:27

from django.db import migrations
import os
import shutil


def migrate_pdf_paths(apps, schema_editor):
    """Move PDF files from pdfs/ to articles/pdfs/ and update database paths"""
    Article = apps.get_model('CMSapp', 'Article')
    
    # Get the media root from settings
    from django.conf import settings
    media_root = settings.MEDIA_ROOT
    
    # Create the new directory if it doesn't exist
    new_dir = os.path.join(media_root, 'articles', 'pdfs')
    os.makedirs(new_dir, exist_ok=True)
    
    # Update all articles with PDF files
    for article in Article.objects.filter(pdf_file__isnull=False).exclude(pdf_file=''):
        old_path = str(article.pdf_file)
        
        # Only update if the path starts with 'pdfs/' (not already 'articles/pdfs/')
        if old_path.startswith('pdfs/') and not old_path.startswith('articles/pdfs/'):
            # Extract the filename
            filename = os.path.basename(old_path)
            new_path = f'articles/pdfs/{filename}'
            
            # Move the physical file if it exists
            old_file_path = os.path.join(media_root, old_path)
            new_file_path = os.path.join(media_root, new_path)
            
            if os.path.exists(old_file_path):
                try:
                    # Move the file
                    shutil.move(old_file_path, new_file_path)
                    print(f"Moved {old_path} to {new_path}")
                except Exception as e:
                    print(f"Error moving {old_path}: {e}")
                    # If file already exists at destination, just update the path
                    if os.path.exists(new_file_path):
                        print(f"File already exists at {new_path}, updating path only")
                    else:
                        continue
            
            # Update the database path
            article.pdf_file = new_path
            article.save(update_fields=['pdf_file'])


def reverse_migrate_pdf_paths(apps, schema_editor):
    """Reverse migration: Move PDF files back from articles/pdfs/ to pdfs/"""
    Article = apps.get_model('CMSapp', 'Article')
    
    from django.conf import settings
    media_root = settings.MEDIA_ROOT
    
    # Create the old directory if it doesn't exist
    old_dir = os.path.join(media_root, 'pdfs')
    os.makedirs(old_dir, exist_ok=True)
    
    # Update all articles with PDF files
    for article in Article.objects.filter(pdf_file__isnull=False).exclude(pdf_file=''):
        new_path = str(article.pdf_file)
        
        # Only update if the path starts with 'articles/pdfs/'
        if new_path.startswith('articles/pdfs/'):
            # Extract the filename
            filename = os.path.basename(new_path)
            old_path = f'pdfs/{filename}'
            
            # Move the physical file if it exists
            new_file_path = os.path.join(media_root, new_path)
            old_file_path = os.path.join(media_root, old_path)
            
            if os.path.exists(new_file_path):
                try:
                    shutil.move(new_file_path, old_file_path)
                except Exception as e:
                    print(f"Error moving {new_path}: {e}")
            
            # Update the database path
            article.pdf_file = old_path
            article.save(update_fields=['pdf_file'])


class Migration(migrations.Migration):

    dependencies = [
        ('CMSapp', '0004_alter_article_pdf_file'),
    ]

    operations = [
        migrations.RunPython(migrate_pdf_paths, reverse_migrate_pdf_paths),
    ]
