"""
Django settings for CMSproject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-dzfm4u_u9hwz07nus$&_^y%z%#8@vnv*nw%7&p5!h=mod4=$$*'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'CMSapp',
    'corsheaders', 
    'chatbot',
    'ratelimit',  # for rate limiting
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True

# # For production, restrict CORS to your frontend domain(s) to prevent unauthorized access
# CORS_ALLOWED_ORIGINS = [
#     'https://yourfrontenddomain.com',  # Replace with your React app's domain
#     'https://www.yourfrontenddomain.com',
# ]  # Remove CORS_ALLOW_ALL_ORIGINS = True for security

ROOT_URLCONF = 'CMSproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CMSproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv("DB_NAME"),
#         'USER': os.getenv("DB_USER"),
#         'PASSWORD': os.getenv("DB_PASSWORD"),
#         'HOST': os.getenv("DB_HOST"),
#         'PORT': os.getenv("DB_PORT"),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "cms",
        'USER': "postgres",
        'PASSWORD': "admin",
        'HOST': "localhost",
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(hours=3),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=30),
    'ROTATE_REFRESH_TOKENS' : True,
    'BLACKLIST_AFTER_ROTATION' : True,
}

# session stored securely on server side (align with view.py 1-hour timeout)
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_AGE = 3600 # auto reset after 1 hour
SESSION_SAVE_EVERY_REQUEST = True # update session on every request for accuracy
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # clear on browser close for security

# cache settings (for potential future caching in views.py)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', # in-memory cache (use Redis for production)
    }
}

# logging for chatbot security monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'chatbot_security.log',
        }, 
    },
    'loggers': {
        'django': {
            'hanlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Store sessions in browser
SESSION_COOKIE_SECURE = False  # Requires HTTPS in production - change True for production
SESSION_COOKIE_HTTPONLY = True  # Prevent JS access
SESSION_COOKIE_SAMESITE = 'Lax'  # Balance security and usability
CSRF_COOKIE_SECURE = False  # CSRF cookie over HTTPS only - change True for production

# HTTPS in production
SECURE_SSL_REDIRECT = False  # Redirect HTTP to HTTPS (set False for local testing) - change True for production
SECURE_HSTS_SECONDS = 0  # Local: 0 (disabled). Production: Set to 31536000 (1 year) for HTTP Strict Transport Security (prevents downgrade attacks).
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # Local: False. Production: Set to True to include subdomains in HSTS.
SECURE_HSTS_PRELOAD = False  # Local: False. Production: Set to True to allow preloading in browsers.
SECURE_CONTENT_TYPE_NOSNIFF = True  # Local/Production: True (always safe; prevents MIME type sniffing attacks).
SECURE_BROWSER_XSS_FILTER = True  # Local/Production: True (always safe; enables browser XSS filtering).
